=== jsatheeshkannan/xmlData/emp.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT employees (employee+,footer)>
<!ELEMENT employee (name,salary)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ATTLIST employee 
aid CDATA #REQUIRED 
version CDATA #IMPLIED
enabled (true|false) "true" 
no_of_course CDATA "5"
fname CDATA #IMPLIED
>
<!ENTITY CopyRights "copyright:@2016">

=== jsatheeshkannan/xmlData/a1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "emp.dtd">
<employees>	
	<employee aid="103" version="1.0" fname="t1">
	<name>nishok</name>
	<salary>1000</salary>
	</employee>
	<employee aid="101" fname="t2">
		<name>kannans</name>
		<salary>2000</salary>
	</employee>
	<employee aid="102" fname="t3">
		<name>satheesh</name>
		<salary>1000</salary>
		
	</employee>
	<footer>&CopyRights;</footer>
</employees>
