<?xml version="1.0" ?>

<!DOCTYPE students  [

<!ELEMENT students (student*) >
<!ELEMENT student (fname,lname,class)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT class (#PCDATA)>
<!ATTLIST student 
id CDATA #REQUIRED
]>

<students>
	<student id="1001">
		<fname>satheesh</fname>
		<lname>kannan</lname>
		<class>x</class>
	</student>
	

</students>